import test from 'ava'
// import bitcoin from 'instances/bitcoin'
import btcSwap from 'swaps/btcSwap'


const secret = '3e0b064c97247732a3b345ce7b2a835d928623cb2871c26db4c2539a38e61a16'
const secretHash = '29c36b8dd380e0426bdc1d834e74a630bfd5d111'


test('check secretHash generated by ripemd160', (t) => {
  // btcSwap.createScript({ btcOwnerSecretHash, btcOwnerPublicKey, ethOwnerPublicKey, lockTime: _lockTime })

  t.pass()
})

// test('my passing test', (t) => {
//   btcSwap.createScript({ btcOwnerSecretHash, btcOwnerPublicKey, ethOwnerPublicKey, lockTime: _lockTime })
//
//   t.pass()
// })
